# file: .travis.yml
language: objective-c
osx_image: xcode8
xcode_project: TableBinding.xcodeproj
xcode_scheme: TableBinding

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N

script:

# - xctool -project TableBinding.xcodeproj -scheme "TableBinding" test | xcpretty -c


- xctool -project TableBinding.xcodeproj -scheme "TableBinding" -sdk macosx10.10 -configuration Debug -destination "platform=OS X" -PBXBuildsContinueAfterErrors=0 test | xcpretty -c


# http://docs.travis-ci.com/user/languages/objective-c/


